
[view_keys.rilsso-spending]
key = "zvknam1qv7yukq7qqqqpqqj0j8vs5t0lkcx44da7aajjv5g7tnntkffgdq9tql352dxznj2vq3rf6z3tv40cgny6dt8vwh74mgktka69xzqgyfyau3e0trkjhr3r9h8vcthpfcplryry5zegsx7t06qmgv3dj7wvfps6csn86lcczzvgf620rkm2df4cjjngs26f98wk7usk9z5cazywv7z8nqpwjzk7r4kw07rm03kqxv8js6zgca9f899xzf44x8pdths3hqrcns6xm0rspg6ujp07"
birthday = 0

[spend_keys]
rilsso-spending = "unencrypted:zsknam1qv7yukq7qqqqpqqj0j8vs5t0lkcx44da7aajjv5g7tnntkffgdq9tql352dxznj2vrd6vc55tk76u9aknjcgatd983yfja3nw3nct0yvrcs6sjq5rc7srafy8hk0q0rrff9hh9s3c8w73casuff45vg9dvfy4k46smaghmcggf620rkm2df4cjjngs26f98wk7usk9z5cazywv7z8nqpwjzk7r4kw07rm03kqxv8js6zgca9f899xzf44x8pdths3hqrcns6xm0rspgjgp42z<<0"

[secret_keys]
rilsso-public = "unencrypted:00c935010365590305e808db7e288f5f126ca91c1c48501aaa113216b2f21233cf"

[public_keys]
rilsso-public = "ED25519_PK_PREFIXtpknam1qprlxxc84kagvnnd8dgl5exasqhzxy9c6azt0k95c2gxfdh8nlxl6qrw70t"

[pkhs]
17C2803AF0792AFB621D9D78821EEB2A80291942 = "rilsso-public"

[payment_addrs]
rilsso-public = "znam1l3p6wck8jgqpfrsa7jdsnl8uqghx6dtn6gd0avtfzdyx69d80uq62za0nefzf0qpz9kdjjl2e5g"

[derivation_paths]
rilsso-spending = "m/32'/877'/0'"
rilsso-public = "m/44'/877'/0'/0'/0'"

[addresses]
rilsso-public = "tnam1qqtu9qp67puj47mzrkwh3qs7av4gq2geggdkzjxw"

[address_vp_types]
