
[view_keys.rilsso-spending]
key = "zvknam1qdfx9vz9qqqqpq96zwzrmfpf0sgg686hswf705r2mykcpfv2mlps3s0l9k266luxh4278797awkwqh3dt2rq2z0hsyh2v62mkfh8x8wfpqzwjs3fjux7cxdzw2akhnmez0m8ttunh2azu64uq0gzmzctaxrxhgzf4kawr7gdzfe4mu0j5zf9dfuctctnkstew26um290y8fkjkv3z9nw5dpzgtkjccc3a34ttf660fw95dh5mz0j5srzaqrcer3w386jjf6q2majp0qzryvrs"
birthday = 0

[spend_keys]
rilsso-spending = "unencrypted:zsknam1qdfx9vz9qqqqpq96zwzrmfpf0sgg686hswf705r2mykcpfv2mlps3s0l9k266luxh593dhggwgc42um7fqcxuy6rq2nmvyw4044wrxjx5k4jjj6v94csgm9kqgnaylas6648vcth5vhr8g4mkyyfj4m54vf054f5l5qtvps2zfe4mu0j5zf9dfuctctnkstew26um290y8fkjkv3z9nw5dpzgtkjccc3a34ttf660fw95dh5mz0j5srzaqrcer3w386jjf6q2majp0q89xfkj<<0"

[secret_keys]
rilsso-public = "unencrypted:003d6c28a4e67619fa783d3865215092a964bbd3880eaee072b5ad3c731f0e9c2a"

[public_keys]
rilsso-public = "ED25519_PK_PREFIXtpknam1qzqnhxtzm7sg20w5a55wz28620hsvgd34ff597wvxdh98kssxt3sc6wakv9"

[pkhs]
D1B46230FD4EF4D175303761D0B06B06A513149F = "rilsso-public"

[payment_addrs]
rilsso-public = "znam1qy47n27agvm4zchkg4cxe22j7njl2wpssupwc8tkcgsprltxm9jgz7l29kcj64d5nw7wxy4fnkz"

[derivation_paths]
rilsso-spending = "m/32'/877'/0'"
rilsso-public = "m/44'/877'/0'/0'/0'"

[addresses]
rilsso-public = "tnam1qrgmgc3sl480f5t4xqmkr59sdvr22yc5nuta2zaq"

[address_vp_types]
